source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SmoothLineView_Example', :exclusive => true do
  pod "SmoothLineView", :path => "../"
  pod "PureLayout"
end

target 'Tests', :exclusive => true do
  pod "SmoothLineView", :path => "../"
end
