source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SmoothLineView_Example', :exclusive => true do
  pod "SmoothLineView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SmoothLineView", :path => "../"

  pod 'FBSnapshotTestCase'
end
